'use client'

import {TypeItem} from "@/types/item";
import {TypeData} from "@/types/data";
import {todayWeek} from "@/utils/date";
import {TypeDesignItem, TypeSchedule} from "@/types/schedule";

export const configAoData: TypeData = {
    locale: 'ko',
    zIndex: 1000,
    width: 1280,
    height: 720,
    backgroundImage: "",
    scheduleStart: todayWeek(),
    scheduleDateFormat: "M/d",
    scheduleWeekFormat: "(eee)",
    scheduleDateDesign: "common",
    scheduleWeekDesign: "common",
    scheduleContentDesign: "individual"
}

export const configAoItems: TypeItem[] = [
    {
        "id": 1,
        "zIndex": 1000,
        "width": 557,
        "height": 100,
        "transform": "translate(610px, 5px)",
        "type": "text",
        "content": "이번주",
        "borderColor": "#006FEE",
        "borderWidth": 0,
        "borderRadius": 0,
        "backgroundColor": "#FFFFFF",
        "color": "#a5c7e9",
        "fontSize": 90,
        "fontName": "NotoSansKRBlack",
        "fontItalic": true,
        "letterSpacing": -10,
        "lineHeight": 1,
        "textAlign": "center",
        "textShadow": "-1px 5px #FFFFFF, 5px 1px #FFFFFF, 5px 5px #FFFFFF, 1px -1px #FFFFFF",
        "boxShadow": "none",
        "opacity": 0
    },
    {
        "id": 2,
        "zIndex": 1002,
        "width": 300,
        "height": 100,
        "transform": "translate(980px, 5px)",
        "type": "text",
        "content": "스케줄",
        "borderColor": "#006FEE",
        "borderWidth": 0,
        "borderRadius": 0,
        "backgroundColor": "#FFFFFF",
        "color": "#53698c",
        "fontSize": 90,
        "fontName": "NotoSansKRBlack",
        "fontItalic": true,
        "letterSpacing": -10,
        "lineHeight": 1,
        "textAlign": "center",
        "textShadow": "-1px 5px #FFFFFF, 5px 1px #FFFFFF, 5px 5px #FFFFFF, 1px -1px #FFFFFF",
        "boxShadow": "none",
        "opacity": 0
    },
    {
        "id": 3,
        "zIndex": 1003,
        "width": 244,
        "height": 100,
        "transform": "translate(1030px, 85px)",
        "type": "text",
        "content": "오후 2시 20분",
        "borderColor": "#006FEE",
        "borderWidth": 2,
        "borderRadius": 20,
        "backgroundColor": "#FFFFFF",
        "color": "#58698b",
        "fontSize": 32,
        "fontName": "NotoSansKRBold",
        "fontItalic": true,
        "letterSpacing": -0.4,
        "lineHeight": 1,
        "textAlign": "right",
        "textShadow": "-1px 1px #FFFFFF, 1px 1px #FFFFFF, 1px 1px #FFFFFF, 1px -1px #FFFFFF",
        "boxShadow": "none",
        "opacity": 0
    },
    {
        "id": 4,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(1030px, 110px)",
        "type": "text",
        "content": "토",
        "borderColor": "#ffffff",
        "borderWidth": 2,
        "borderRadius": 500,
        "backgroundColor": "#536a8b",
        "color": "#fcfcfc",
        "fontSize": 29,
        "fontName": "NotoSansKRMedium",
        "fontItalic": true,
        "letterSpacing": 7.6,
        "lineHeight": 1.3,
        "textAlign": "center",
        "textShadow": "none",
        "boxShadow": "none",
        "opacity": 100,
        "padding": 0
    },
    {
        "id": 5,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(980px, 110px)",
        "type": "text",
        "content": "금",
        "borderColor": "#ffffff",
        "borderWidth": 2,
        "borderRadius": 500,
        "backgroundColor": "#536a8b",
        "color": "#fcfcfc",
        "fontSize": 29,
        "fontName": "NotoSansKRMedium",
        "fontItalic": true,
        "letterSpacing": 7.6,
        "lineHeight": 1.3,
        "textAlign": "center",
        "textShadow": "none",
        "boxShadow": "none",
        "opacity": 100,
        "padding": 0
    },
    {
        "id": 6,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(930px, 110px)",
        "type": "text",
        "content": "목",
        "borderColor": "#ffffff",
        "borderWidth": 2,
        "borderRadius": 500,
        "backgroundColor": "#536a8b",
        "color": "#fcfcfc",
        "fontSize": 29,
        "fontName": "NotoSansKRMedium",
        "fontItalic": true,
        "letterSpacing": 7.6,
        "lineHeight": 1.3,
        "textAlign": "center",
        "textShadow": "none",
        "boxShadow": "none",
        "opacity": 100,
        "padding": 0
    },
    {
        "id": 7,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(880px, 110px)",
        "type": "text",
        "content": "수",
        "borderColor": "#ffffff",
        "borderWidth": 2,
        "borderRadius": 500,
        "backgroundColor": "#536a8b",
        "color": "#fcfcfc",
        "fontSize": 29,
        "fontName": "NotoSansKRMedium",
        "fontItalic": true,
        "letterSpacing": 7.6,
        "lineHeight": 1.3,
        "textAlign": "center",
        "textShadow": "none",
        "boxShadow": "none",
        "opacity": 100,
        "padding": 0
    },
    {
        "id": 8,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(830px, 110px)",
        "type": "text",
        "content": "화",
        "borderColor": "#ffffff",
        "borderWidth": 2,
        "borderRadius": 500,
        "backgroundColor": "#536a8b",
        "color": "#fcfcfc",
        "fontSize": 29,
        "fontName": "NotoSansKRMedium",
        "fontItalic": true,
        "letterSpacing": 7.6,
        "lineHeight": 1.3,
        "textAlign": "center",
        "textShadow": "none",
        "boxShadow": "none",
        "opacity": 100,
        "padding": 0
    },
    {
        "id": 9,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(780px, 110px)",
        "type": "text",
        "content": "월",
        "borderColor": "#ffffff",
        "borderWidth": 2,
        "borderRadius": 500,
        "backgroundColor": "#536a8b",
        "color": "#fcfcfc",
        "fontSize": 29,
        "fontName": "NotoSansKRMedium",
        "fontItalic": true,
        "letterSpacing": 7.6,
        "lineHeight": 1.3,
        "textAlign": "center",
        "textShadow": "none",
        "boxShadow": "none",
        "opacity": 100,
        "padding": 0
    },
    {
        "id": 10,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(730px, 110px)",
        "type": "text",
        "content": "일",
        "borderColor": "#ffffff",
        "borderWidth": 2,
        "borderRadius": 500,
        "backgroundColor": "#b3b3b3",
        "color": "#fcfcfc",
        "fontSize": 29,
        "fontName": "NotoSansKRMedium",
        "fontItalic": true,
        "letterSpacing": 7.6,
        "lineHeight": 1.3,
        "textAlign": "center",
        "textShadow": "none",
        "boxShadow": "none",
        "opacity": 100,
        "padding": 0
    }
];

export const configDesignDate: TypeDesignItem[] = [
    {
        "id": 1,
        "zIndex": 1000,
        "width": 130,
        "height": 50,
        "transform": "translate(0px, 32px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "right",
        "color": "#54698c",
        "fontItalic": true,
        "fontName": "NotoSansKRSemiBold",
        "fontSize": 60,
        "letterSpacing": -3.5
    },
    {
        "id": 2,
        "zIndex": 1000,
        "width": 130,
        "height": 50,
        "transform": "translate(48px, 128px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "right",
        "color": "#54698c",
        "fontItalic": true,
        "fontName": "NotoSansKRSemiBold",
        "fontSize": 60,
        "letterSpacing": -3.5
    },
    {
        "id": 3,
        "zIndex": 1000,
        "width": 130,
        "height": 50,
        "transform": "translate(9px, 226px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "right",
        "color": "#54698c",
        "fontItalic": true,
        "fontName": "NotoSansKRSemiBold",
        "fontSize": 60,
        "letterSpacing": -3.5
    },
    {
        "id": 4,
        "zIndex": 1000,
        "width": 130,
        "height": 50,
        "transform": "translate(50px, 327px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "right",
        "color": "#54698c",
        "fontItalic": true,
        "fontName": "NotoSansKRSemiBold",
        "fontSize": 60,
        "letterSpacing": -3.5
    },
    {
        "id": 5,
        "zIndex": 1000,
        "width": 130,
        "height": 50,
        "transform": "translate(4px, 428px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "right",
        "color": "#54698c",
        "fontItalic": true,
        "fontName": "NotoSansKRSemiBold",
        "fontSize": 60,
        "letterSpacing": -3.5
    },
    {
        "id": 6,
        "zIndex": 1000,
        "width": 130,
        "height": 50,
        "transform": "translate(30px, 530px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "right",
        "color": "#54698c",
        "fontItalic": true,
        "fontName": "NotoSansKRSemiBold",
        "fontSize": 60,
        "letterSpacing": -3.5
    },
    {
        "id": 7,
        "zIndex": 1000,
        "width": 130,
        "height": 50,
        "transform": "translate(3px, 627px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "right",
        "color": "#54698c",
        "fontItalic": true,
        "fontName": "NotoSansKRSemiBold",
        "fontSize": 60,
        "letterSpacing": -3.5
    }
];

export const configDesignWeek: TypeDesignItem[] = [
    {
        "id": 1,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(135px, 40px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "left",
        "color": "#53698e",
        "fontName": "NotoSansKRBold",
        "fontSize": 31,
        "fontItalic": true,
        "letterSpacing": -1.9
    },
    {
        "id": 2,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(183px, 135px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "left",
        "color": "#53698e",
        "fontName": "NotoSansKRBold",
        "fontSize": 31,
        "fontItalic": true,
        "letterSpacing": -1.9
    },
    {
        "id": 3,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(144px, 234px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "left",
        "color": "#53698e",
        "fontName": "NotoSansKRBold",
        "fontSize": 31,
        "fontItalic": true,
        "letterSpacing": -1.9
    },
    {
        "id": 4,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(188px, 336px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "left",
        "color": "#53698e",
        "fontName": "NotoSansKRBold",
        "fontSize": 31,
        "fontItalic": true,
        "letterSpacing": -1.9
    },
    {
        "id": 5,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(140px, 437px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "left",
        "color": "#53698e",
        "fontName": "NotoSansKRBold",
        "fontSize": 31,
        "fontItalic": true,
        "letterSpacing": -1.9
    },
    {
        "id": 6,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(169px, 540px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "left",
        "color": "#53698e",
        "fontName": "NotoSansKRBold",
        "fontSize": 31,
        "fontItalic": true,
        "letterSpacing": -1.9
    },
    {
        "id": 7,
        "zIndex": 1000,
        "width": 50,
        "height": 50,
        "transform": "translate(138px, 639px)",
        "backgroundColor": "#FFFFFF",
        "textAlign": "left",
        "color": "#53698e",
        "fontName": "NotoSansKRBold",
        "fontSize": 31,
        "fontItalic": true,
        "letterSpacing": -1.9
    }
];

export const configAoSchedule: TypeSchedule[] = [
    {
        "id": 1,
        "content": "쉬는시간",
        "zIndex": 1000,
        "width": 300,
        "height": 50,
        "transform": "translate(213px, 30px)",
        "textAlign": "left",
        "fontSize": 46,
        "color": "#b3b3b3",
        "fontItalic": true,
        "fontName": "NotoSansKRBlack"
    },
    {
        "id": 2,
        "content": "잡담방송",
        "zIndex": 1000,
        "width": 300,
        "height": 50,
        "transform": "translate(262px, 127px)",
        "textAlign": "left",
        "fontSize": 46,
        "color": "#48567b",
        "fontItalic": true,
        "fontName": "NotoSansKRBlack"
    },
    {
        "id": 3,
        "content": "안보고 캐릭터 그리기",
        "zIndex": 1000,
        "width": 500,
        "height": 50,
        "transform": "translate(215px, 229px)",
        "textAlign": "left",
        "fontSize": 46,
        "color": "#48567b",
        "fontItalic": true,
        "fontName": "NotoSansKRBlack"
    },
    {
        "id": 4,
        "content": "노래 공부를 해 보자",
        "zIndex": 1000,
        "width": 500,
        "height": 50,
        "transform": "translate(265px, 335px)",
        "textAlign": "left",
        "fontSize": 46,
        "color": "#48567b",
        "fontItalic": true,
        "fontName": "NotoSansKRBlack"
    },
    {
        "id": 5,
        "content": "쉬는시간",
        "zIndex": 1000,
        "width": 300,
        "height": 50,
        "transform": "translate(231px, 433px)",
        "textAlign": "left",
        "fontSize": 46,
        "color": "#b3b3b3",
        "fontItalic": true,
        "fontName": "NotoSansKRBlack"
    },
    {
        "id": 6,
        "content": "김아오 참치단 커머셜 데이",
        "zIndex": 1000,
        "width": 600,
        "height": 50,
        "transform": "translate(267px, 533px)",
        "textAlign": "left",
        "fontSize": 46,
        "color": "#48567b",
        "fontItalic": true,
        "fontName": "NotoSansKRBlack"
    },
    {
        "id": 7,
        "content": "잡담방송",
        "zIndex": 1000,
        "width": 300,
        "height": 50,
        "transform": "translate(223px, 633px)",
        "textAlign": "left",
        "fontSize": 46,
        "color": "#48567b",
        "fontItalic": true,
        "fontName": "NotoSansKRBlack"
    }
]
